version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Esto te permite conectar un programa como DBeaver o pgAdmin desde Windows

  web:
    build: .
    container_name: portafolio_web_local
    # En local es mejor usar el runserver para ver los cambios en tiempo real (Hot Reload)
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000" # Mapeamos el puerto para que entres por localhost:8000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: portafolio_nginx_local
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    # Lo comentamos por ahora para que no te de error si Nginx no encuentra los archivos estáticos aún
    # profiles: ["production"] 

volumes:
  postgres_data:
  static_volume:
  media_volume: