# Generated by Django 6.0.3 on 2026-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion_corta', models.TextField(max_length=300, verbose_name='Descripción Corta')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada')),
                ('tecnologias', models.CharField(max_length=200, verbose_name='Tecnologías (Ej: Django, React)')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen de Portada')),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='Enlace GitHub')),
                ('link_video', models.URLField(blank=True, null=True, verbose_name='Enlace Video (YouTube)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
