# Generated by Django 6.0.3 on 2026-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'mensaje de contacto', 'verbose_name_plural': 'mensajes de contacto'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='contestado',
            field=models.BooleanField(default=False, verbose_name='¿Fue contestado?'),
        ),
    ]
