# Generated by Django 6.0.3 on 2026-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contacto_options_contacto_contestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/videos/'),
        ),
    ]
